### ISSUE TITLE
Dartdoc does not accept super calls from mixins

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dartdoc#1541]
To reproduce (using flutter):
```
$ flutter create -t plugin test_plugin
$ cd test_plugin
```
Replace `lib/test_plugin.dart` with

```
import 'package:flutter/widgets.dart';

class A extends StatefulWidget {
  @override
  _AState createState() => new _AState();
}

class _AState extends State<A> with SingleTickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return new Container();
  }
}
```

Run 
```
$ export FLUTTER_ROOT=~/path/to/flutter
$ ~/path/to/flutter/bin/cache/dart-sdk/bin/dartdoc
Generating documentation for 'test_plugin' into /Users/sigurdm/projects/test_plugin/doc/api/

parsing lib/test_plugin.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/collection/collection.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/developer/developer.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/internal/internal.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/io/io.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/isolate/isolate.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/async/async.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/convert/convert.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/typed_data/typed_data.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/_empty.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/math/math.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/core/core.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/_http/http.dart...
parsing /Users/sigurdm/projects/flutter/bin/cache/pkg/sky_engine/lib/ui/ui.dart...
parsed 12 files in 8.8 seconds
[error] The class 'SingleTickerProviderStateMixin' can't be used as a mixin because it extends a class other than Object. at lib/test_plugin.dart, line 8.
[error] The class 'SingleTickerProviderStateMixin' can't be used as a mixin because it references 'super'. at lib/test_plugin.dart, line 8.

Generation failed: encountered 2 analysis errors.
```

**Comment by sigurdm** [comment]
cc @jcollins-g

**Comment by mit-mit** [comment]
It's also failing for me on some of the packages we have already published, for example on `device_info`:

```
Generating documentation for 'device_info' into C:\Users\mit\dev\github\plugins\packages\device_info\doc\api\

parsing lib\device_info.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\collection\collection.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\developer\developer.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\internal\internal.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\io\io.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\isolate\isolate.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\async\async.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\convert\convert.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\typed_data\typed_data.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\_empty.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\math\math.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\core\core.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\_http\http.dart...
parsing C:\Users\mit\dev\github\flutter\bin\cache\pkg\sky_engine\lib\ui\ui.dart...
parsed 12 files in 7.2 seconds

Generation failed: Unknown type GenericFunctionTypeElementImpl
package:dartdoc/src/model.dart 1991                                                           new ModelElement.from
package:dartdoc/src/model.dart 1188                                                           Field._setModelType
package:dartdoc/src/model.dart 1055                                                           new Field
package:dartdoc/src/model.dart 1956                                                           new ModelElement.from
package:dartdoc/src/model.dart 821                                                            Class._allFields.<fn>
dart:core                                                                                     Iterable.toList
```

**Comment by mit-mit** [comment]
Looks like "my issue" is https://github.com/dart-lang/dartdoc/pull/1497, which was fixed later than the current version of dartdoc inside flutter...

**Comment by sigurdm** [comment]
The problem with the super mixin seems to be still present in dartdoc version: 0.14.1 from Dart VM version: 2.0.0-dev.8.0 (Fri Nov 17 13:53:29 2017) on "macos_ia32"

**Comment by jcollins-g** [comment]
@mit-mit  :  dartdoc used by flutter is at 0.14.1: https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L13

**Comment by jcollins-g** [comment]
This looks like more fallout of the general problem that dartdoc does not obey analysis_options files.  A side-effect of #1524 will make the general problem more likely to get fixed (reduced number of ways that the analyzer is invoked to one inside dartdoc) but there's no fix on deck yet for this or the specific issue filed.
