### ISSUE TITLE
The list of libraries in the left side doesn't stroke deprecated ones

### ISSUE THREAD

**Issue by dynaxis** [dart-lang/dartdoc#866]
I'm trying the new `api.dartlang.org`. `dart:profiler` has been deprecated and the fact is well presented with a stroke in the name of it in the main list of libraries in the front page. But the left side section listing library names doesn't reflect the fact.

I'm filing this issue assuming `api.dartlang.org` is already using the latest version of `dartdoc`.

![ok](https://cloud.githubusercontent.com/assets/570120/9512390/443b2368-4cbc-11e5-9926-581654e5f42f.png)
![nay](https://cloud.githubusercontent.com/assets/570120/9512391/4792d0b0-4cbc-11e5-9c19-c22421dcfc3b.png)

**Comment by sethladd** [comment]
Good call, thanks! We should be able to fix this.

**Comment by sethladd** [comment]
addressed by https://github.com/dart-lang/dartdoc/pull/871

**Comment by sethladd** [comment]
Fixed on master.

**Comment by dynaxis** [comment]
@sethladd Is the fix for this issue in the 1.12.0 release? I still see `dart:profiler` not stroked out in the left side.

**Comment by sethladd** [comment]
Unfortunately, it didn't make the cut. Hopefully we get into a 1.12.1. The version in pub should work.
